version: '3'
services:
  blog-api:
    image: 'blog-api:v1.0.1'
    restart: always
    privileged: false
    container_name: blog-api
    networks:
      - blog-backend
    volumes:
      - ./app/logs:/logs
      - /etc/timezone:/etc/timezone
    expose:
      - 8181
    environment:
      - BLOG-MYSQL-USER=root
      - BLOG-MYSQL-PWD=123456
      - BLOG-REDIS-PWD=123456
      - BLOG-MQ-USER=guest
      - BLOG-MQ-PWD=guest
  blog-admin:
    image: 'blog-admin:v1.0.1'
      restart: always
      privileged: false
      container_name: blog-admin
      networks:
        - blog-frontend
      volumes:
        - /etc/timezone:/etc/timezone
      expose:
        - 8282
  blog-front:
    image: 'blog-front:v1.0.1'
      restart: always
      privileged: false
      container_name: blog-front
      volumes:
        - /etc/timezone:/etc/timezone
      networks:
        - blog-frontend
      expose:
        - 8383
      - blog-extranet
  nginx-proxy:
    container_name: blog-nginx
    image: 'nginx:1.16-alpine'
    restart: always
    privileged: false
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/full_chain.pem:/etc/nginx/certs/full_chain.pem
      - ./nginx/certs/private.key:/etc/nginx/certs/private.key
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - blog-backend
      - blog-frontend

networks:
  blog-backend:
    external: true
  blog-frontend:
    external: true
