version: '3'
services:
  blog-api:
    image: ''
    restart: always
    privileged: false
    container_name: blog-api
    networks:
      - blog-extranet
    volumes:
      - ./app/logs:/logs
      - /etc/timezone:/etc/timezone
    expose:
      - 8181
    environment:
      - BLOG-MYSQL-USER=
      - BLOG-MYSQL-PWD=
      - BLOG-REDIS-PWD=
      - BLOG-MQ-USER=
      - BLOG-MQ-PWD=
  blog-admin:
    image: ''
      restart: always
      privileged: false
      container_name: blog-admin
      networks:
        - blog-extranet
      expose:
        - 8282
  blog-front:
    image: ''
      restart: always
      privileged: false
      container_name: blog-front
      networks:
        - blog-extranet
      expose:
        - 8383

networks:
  blog-extranet:
    driver: bridge