version: '3'
services:
  db:
    container_name: blog-mysql
    image: 'mysql/mysql-server:8.0'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456  #root密码
    volumes:
      - ./mysql/data:/var/lib/mysql #数据文件挂载
      - ./mysql/conf:/etc/mysql/conf.d #配置文件挂载
      - ./mysql/log:/var/log/mysql #日志文件挂载
    privileged: false
    ports:
      - 3306:3306
    networks:
      - blog-nextwork
  redis:
    container_name: blog-redis
    image: 'redis:6.0'
    restart: always
    privileged: false
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/conf/redis.conf  #配置文件挂载
    command: redis-server /conf/redis.conf
    ports:
      - 6379:6379
    networks:
      - blog-nextwork
  mq:
    container_name: blog-rabbitmq
    image: 'rabbitmq:3.8.9-management-alpine'
    restart: always
    privileged: false
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - ./rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - blog-nextwork
  es:
    container_name: blog-es
    image: 'gagara/elasticsearch-oss-arm64:latest'
    restart: always
    privileged: false
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - ./es/plugins:/usr/share/elasticsearch/plugins
      - ./es/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - blog-nextwork
  kibana:
    image: 'gagara/kibana-oss-arm64:latest'
    container_name: blog-kibana
    restart: always
    depends_on:
      - es #kibana在elasticsearch启动之后再启动
    environment:
      - "ELASTICSEARCH_HOSTS=http://es:9200"
    ports:
      - 5601:5601
    networks:
      - blog-nextwork
  logstash:
    image: 'gagara/logstash-oss-arm64:latest'
    container_name: blog-logstash
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - es #kibana在elasticsearch启动之后再启动
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
    networks:
      - blog-nextwork
  nginx:
    container_name: blog-nginx
    image: 'nginx:1.18'
    restart: always
    privileged: false
    volumes:
      #- ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - blog-nextwork
networks:
  blog-nextwork:
    driver: bridge