pipeline {
    agent any
    stages {
        stage('拉取代码') {
            steps {
                echo "开始拉取代码: 位置：${WORKSPACE}"
                 script {
                        if(!fileExists("${WORKSPACE}/blog")){
                            sh "git clone git@github.com:h-dj/blog.git"
                            dir("${WORKSPACE}/blog"){
                                sh "git checkout develop"
                                sh "git branch"
                            }
                         }else{
                            dir("${WORKSPACE}/blog"){
                                sh "git pull"
                            }
                         }
                }
                echo "开始拉取代码: 完成 "
            }
        }
        stage('构建jar包') {
            steps {
                dir("${WORKSPACE}/blog/hdj-blog"){
                    sh "${MAVEN_HOME}/bin/mvn -DskipTests=true clean package -P prod_lib"
                    sh "ls -l ./target"
                }
            }
        }
        stage('发送至指定服务器') {
                     steps {
                          sh 'date'
                          echo "项目构建结果路径：${WORKSPACE}"
                          dir("${WORKSPACE}/blog/hdj-blog"){
                            sh "rsync -avu --progress -e 'ssh -p ${PORT}' ./target/hdj-blog-0.0.1-SNAPSHOT.jar ./target/lib ./Dockerfile   ${USER}@${HOST}:/home/blog/blog/app"
                          }
                          echo '发送成功'
                       }
               }
        stage('项目启动') {
                     steps {
                          sh "ssh ${USER}@${HOST} -p 22022 docker-compose -f /home/blog/blog/docker-compose.yaml up -d --build"
                          sleep 2
                          sh "ssh ${USER}@${HOST} -p 22022 docker logs blog-api"
                       }
                     }
    }
    post {
            success {
                echo 'success'
            }
            unstable {
                echo 'I am unstable :/'
            }
            failure {
                echo 'failed'
            }
            changed {
                echo 'Things were different before...'
            }
        }
}