# 生产阶段(用nginx简洁版镜像)
FROM arm64v8/nginx:1.19.6-alpine as production-stage

MAINTAINER jiajian.java@gmail.com

# 直接复制构建阶段生成在dist的代码到nginx的html目录下
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
# 对外暴露nginx端口
EXPOSE 80
