pipeline {
    agent any
    stages {
        stage('拉取代码') {
            steps {
                echo "开始拉取代码: 位置：${WORKSPACE}"
                 script {
                        if(!fileExists("${WORKSPACE}/blog")){
                            sh "git clone git@github.com:h-dj/blog.git"
                            dir("${WORKSPACE}/blog"){
                                sh "git checkout develop"
                                sh "git branch"
                            }
                         }else{
                            dir("${WORKSPACE}/blog"){
                                sh "git pull"
                            }
                         }
                }
                echo "开始拉取代码: 完成 "
            }
        }
        stage('构建') {
            steps {
              dir("${WORKSPACE}/blog/hdj-blog-front"){
                sh "/usr/bin/npm install"
                sh "/usr/bin/npm run build:prod"
              }
            }
        }
        stage('发送至指定服务器') {
                     steps {
                          sh 'date'
                          echo "项目构建结果路径：${WORKSPACE}"
                          dir("${WORKSPACE}/blog/hdj-blog-front"){
                            sh "rsync -avu --progress  ./dist/**  ${user}@${host}:/home/blog/blog/nginx/www/front"
                          }
                          echo '发送成功'
                       }
                    }
                }
    post {
            success {
                echo 'success'
            }
            unstable {
                echo 'I am unstable :/'
            }
            failure {
                echo 'failed'
            }
            changed {
                echo 'Things were different before...'
            }
        }
}
